// DOM interaction tests; this is not a browser screenshot or visual-layout test.
const {JSDOM,VirtualConsole}=require('jsdom');
const {spawn}=require('node:child_process');
const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');const data=fs.mkdtempSync(path.join(os.tmpdir(),'testagent-ui-'));const port=18769;const url=`http://127.0.0.1:${port}`;
const server=spawn(process.env.PYTHON||'python3',['-m','testagent.server','--port',String(port),'--data',data],{cwd:root,env:{...process.env,PYTHONPATH:path.join(root,'src')},stdio:['ignore','pipe','pipe']});
let logs='';server.stdout.on('data',d=>logs+=d);server.stderr.on('data',d=>logs+=d);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,message){for(let i=0;i<100;i++){if(await fn())return;await sleep(50);}throw Error(message+'\n'+logs);}
let dom;
(async()=>{await until(async()=>{try{return (await fetch(url+'/api/health')).ok;}catch{return false;}},'server did not start');
const errors=[];const console=new VirtualConsole();console.on('jsdomError',e=>errors.push(e.message));
dom=await JSDOM.fromURL(url,{runScripts:'dangerously',resources:'usable',pretendToBeVisual:true,virtualConsole:console,beforeParse(w){w.fetch=(u,o)=>fetch(new URL(u,url),o);w.confirm=()=>true;w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};Object.defineProperty(w,'innerWidth',{value:1440});}});
const w=dom.window,d=w.document;
const button=text=>[...d.querySelectorAll('button')].find(e=>e.textContent===text);
const set=(id,v)=>{const e=d.getElementById(id);assert.ok(e,'missing '+id);e.value=v;e.dispatchEvent(new w.Event('change',{bubbles:true}));};
const submit=()=>d.getElementById('form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
const route=async hash=>{w.location.hash=hash;await sleep(100);};
await until(()=>button('新建任务'),'initial tasks');
await route('#devices');button('添加设备').click();await until(()=>d.getElementById('f-name'),'device form');set('f-name','控制器 A');set('f-address','sim://a');set('f-username','tester');submit();await until(()=>!d.getElementById('dialog').open,'device save');await until(()=>d.body.textContent.includes('控制器 A'),'saved row visible');
await route('#environments');button('新建环境').click();await until(()=>d.getElementById('role-rows'),'empty role form');
assert.equal(d.getElementById('save').disabled,false);assert.equal(d.getElementById('add-role').disabled,false);button('关闭').click();
await route('#skills');button('编写助手').click();await until(()=>d.getElementById('authoring-prompt'),'authoring dialog');
assert.equal(d.getElementById('dialog').open,true);assert.equal(d.getElementById('save').hidden,true);
const prompt=d.getElementById('authoring-prompt');assert.ok(prompt.value.includes('testagent-skill-author/SKILL.md'));assert.ok(prompt.value.includes('本次任务场景'));
const download=d.querySelector('#fields a');assert.equal(download.getAttribute('href'),'/api/authoring-skill');assert.ok((await fetch(download.href)).ok);
let copied;Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async text=>{copied=text;}},configurable:true});
button('复制提示词').click();await until(()=>d.getElementById('authoring-copy-status').textContent==='已复制','copy prompt');assert.equal(copied,prompt.value);
w.navigator.clipboard.writeText=async()=>{throw Error('clipboard denied');};button('复制提示词').click();await until(()=>d.getElementById('authoring-copy-status').textContent.includes('Ctrl+C'),'manual copy fallback');assert.equal(prompt.selectionEnd,prompt.value.length);
button('关闭').click();assert.equal(d.getElementById('dialog').open,false);
button('导入模拟样例').click();await until(()=>d.body.textContent.includes('诊断视图检查（模拟）'),'skill import');
await route('#environments');button('新建环境').click();await until(()=>d.querySelector('[data-environment-role]'),'role dropdown');
assert.equal(d.querySelector('#role-rows input'),null);assert.ok([...d.querySelector('[data-environment-role]').options].some(o=>o.value==='controller'));assert.ok(d.querySelector('[data-environment-role]').textContent.includes('模拟控制器（controller）'));assert.equal(d.getElementById('add-role').disabled,false);
button('移除').click();assert.equal(d.getElementById('save').disabled,true);assert.equal(d.getElementById('add-role').disabled,false);button('添加角色').click();assert.equal(d.querySelectorAll('[data-environment-role]').length,1);assert.equal(d.getElementById('save').disabled,false);
d.querySelector('[data-environment-role]').value='controller';set('f-name','环境 A');submit();await until(()=>!d.getElementById('dialog').open,'environment save');await until(()=>d.body.textContent.includes('环境 A'),'saved row visible');
// Removing a Skill preserves the existing environment role while bundled scenario roles remain available.
await route('#skills');button('删除').click();await until(()=>!d.body.textContent.includes('诊断视图检查（模拟）'),'skill removed');
await route('#environments');button('编辑').click();await until(()=>d.querySelector('[data-environment-role]'),'historical role');assert.ok([...d.querySelector('[data-environment-role]').options].some(o=>o.value==='controller'));assert.ok(d.querySelector('[data-environment-role]').textContent.includes('已有角色'));assert.equal(d.getElementById('save').disabled,false);submit();await until(()=>!d.getElementById('dialog').open,'historical environment saved');
button('新建环境').click();await until(()=>d.getElementById('role-hint'),'new empty environment');assert.ok(d.querySelector('[data-environment-role]'));assert.equal(d.getElementById('save').disabled,false);button('关闭').click();
await route('#skills');button('导入模拟样例').click();await until(()=>d.body.textContent.includes('诊断视图检查（模拟）'),'skill reimport');
await route('#tasks');button('新建任务').click();await until(()=>d.querySelector('[data-role]'),'dynamic role form');set('f-title','第一条任务');submit();await until(()=>button('确认预览并继续'),'preview visible');assert.equal(button('授权此操作'),undefined);button('确认预览并继续').click();await until(()=>button('授权此操作'),'approval visible');button('授权此操作').click();await until(()=>d.querySelector('.badge.succeeded'),'task success');const firstHash=w.location.hash;await until(()=>d.body.textContent.includes('flag-present'),'saved row visible');
await route('#tasks');button('新建任务').click();await until(()=>d.querySelector('[data-role]'),'second task form');set('f-title','第二条任务');submit();await until(()=>button('确认预览并继续'),'second preview');button('确认预览并继续').click();await until(()=>button('授权此操作'),'second approval');button('授权此操作').click();await until(()=>d.querySelector('.badge.succeeded'),'second success');assert.ok(d.querySelector('#task-heading h2').textContent.includes('第二条任务'));
await route(firstHash);await until(()=>d.querySelector('#task-heading h2')?.textContent==='第一条任务','history task identity');
// Isolated view fixture: verify append-only rendering, declared links and diff evidence.
const fixtureId=firstHash.split('/')[1];
const fixtureData=await (await fetch(url+'/api/tasks/'+fixtureId)).json();
fixtureData.task.status='running';
fixtureData.workloads=[{id:'load-fixture',name:'port1',role:'client',state:'running',spec:{driver:'iperf3',duration:60},status:{},samples:[{name:'bandwidth',value:100,unit:'bit/s',at:100,clock:'collection'},{name:'bandwidth',value:200,unit:'bit/s',at:101,clock:'collection'}]}];
const snap=fixtureData.task.snapshot;
snap.roles.switch='fixture-switch';snap.devices['fixture-switch']={name:'交换机 CE',address:'sim://switch'};
const contract=JSON.parse(snap.skill.files['contract.json']);contract.topology=[{from:'controller',to:'switch',label:'管理网络'}];snap.skill.files['contract.json']=JSON.stringify(contract);
fixtureData.comparisons=[{id:'config',name:'交换机配置',role:'switch',available:true,changed:true,before:{text:'vlan 10',operation_id:'capture-before'},after:{text:'vlan 20',operation_id:'capture-after'},diff:'--- before\n+++ after\n-vlan 10\n+vlan 20'}];
let nextSeq=fixtureData.events.at(-1).seq;
const emit=(kind,payload)=>fixtureData.events.push({seq:++nextSeq,kind,payload,at:new Date().toISOString()});
const originalFetch=w.fetch;
w.fetch=async(u,o)=>String(u).startsWith('/api/tasks/'+fixtureId+'?')?{ok:true,json:async()=>({...fixtureData,events:fixtureData.events.filter(e=>e.seq>Number(new URL(u,url).searchParams.get('after')))})}:originalFetch(u,o);
emit('agent.chunk',{text:'正在'});emit('agent.chunk',{text:'检查交换机'});
await w.renderDetail(fixtureId);
assert.equal(d.querySelectorAll('.load-chart polyline').length,1);assert.ok(d.getElementById('task-workloads').textContent.includes('200.00 bit/s'));assert.ok(button('停止此负载'));
assert.equal(d.querySelectorAll('.topology-link').length,1);assert.equal(d.querySelectorAll('.device-node').length,2);
assert.equal(d.querySelector('#chat-messages .message-text').textContent,'正在检查交换机');
assert.ok(d.querySelector('.diff-add').textContent.includes('+++ after'));assert.ok(d.querySelector('#task-comparisons').textContent.includes('发现差异'));
const editor=d.getElementById('task-message'),firstLog=d.querySelector('#task-events .event'),details=firstLog.querySelector('details');
editor.value='正在输入的要求';editor.focus();editor.setSelectionRange(2,5);details.open=true;
const chatPane=d.getElementById('chat-messages');Object.defineProperty(chatPane,'scrollHeight',{value:1000,configurable:true});Object.defineProperty(chatPane,'clientHeight',{value:100,configurable:true});chatPane.scrollTop=30;
emit('agent.chunk',{text:'，配置已读取。'});emit('tool.started',{id:'capture-after',device_id:'fixture-switch'});emit('tool.finished',{id:'capture-after',output:{text:'vlan 20'}});
await w.renderDetail(fixtureId);
assert.equal(d.getElementById('task-message'),editor);assert.equal(editor.value,'正在输入的要求');assert.equal(editor.selectionStart,2);assert.equal(editor.selectionEnd,5);assert.equal(d.activeElement,editor);
assert.equal(d.querySelector('#task-events .event'),firstLog);assert.equal(details.open,true);assert.equal(chatPane.scrollTop,30);assert.equal(d.getElementById('latest-chat').hidden,false);
assert.equal(d.querySelectorAll('#chat-messages .message').length,1);
d.querySelector('[data-device-role="switch"]').dispatchEvent(new w.MouseEvent('click',{bubbles:true}));
assert.equal(d.getElementById('device-filter-label').textContent,'当前设备角色：switch');assert.ok(firstLog.hidden);assert.ok(!d.querySelector('[data-operation="capture-after"]').hidden);
button('显示全部设备').click();assert.equal(firstLog.hidden,false);button('回到最新对话').click();assert.equal(chatPane.scrollTop,1000);
w.fetch=originalFetch;
await route('#settings');button('添加后端').click();await until(()=>d.getElementById('f-base_url'),'profile form');set('f-name','内网 API');set('f-base_url','http://127.0.0.1:9/v1');set('f-api_key','ui-fixture-secret');submit();await until(()=>!d.getElementById('dialog').open,'profile save');await until(()=>d.body.textContent.includes('内网 API'),'saved row visible');assert.ok(!d.body.textContent.includes('ui-fixture-secret'));
button('离线工具库').click();await until(()=>d.getElementById('import-tool'),'offline tools');button('关闭').click();
await route('#tasks');button('网卡极限带宽测试').click();await until(()=>d.querySelector('[data-param=mode]'),'preset parameters');
assert.equal(d.getElementById('dialog-title').textContent,'网卡极限带宽测试');assert.equal(d.querySelector('[data-param=mode]').value,'单端口');assert.ok(d.querySelector('[data-param=mode]').textContent.includes('整卡双端口'));assert.ok(d.querySelector('[data-param=client2_interface]'));assert.ok(d.querySelector('[data-param=server2_ip]'));assert.equal(d.querySelector('[data-param=port2]').value,'5202');assert.ok(!d.getElementById('f-backend').textContent.includes('模拟'));button('关闭').click();
assert.deepEqual(errors,[]);process.stdout.write('UI DOM checks passed: role selection, mandatory preview, task completion, declared topology, configuration diff, stable editor and logs, merged chunks, scroll controls, backend configuration.\n');
})().catch(e=>{process.stderr.write(e.stack+'\n');process.exitCode=1;}).finally(async()=>{if(dom)dom.window.close();server.kill('SIGTERM');await new Promise(r=>server.once('exit',r));fs.rmSync(data,{recursive:true,force:true});});
